### ISSUE TITLE
PTQ for BERT

### ISSUE THREAD

**Issue by qingswu** [IntelLabs/FP8-Emulation-Toolkit#2]
Hi, I checked the PTQ example code, it's using BN to collecting stats during PTQ, is there any plan to providing an example for models without BN, such as transformers? I see stats collection code is already there.

**Comment by nkmellem** [comment]
Yes, BERT will be added in the next release. Check back in about 2 weeks.

**Comment by nkmellem** [comment]
@qingswu , the new release has the bert example. You can play around with it.
