### ISSUE TITLE
examples/inference/bert readme instructions for FP8 

### ISSUE THREAD

**Issue by willwray** [IntelLabs/FP8-Emulation-Toolkit#6]
Hello,

Thanks for publishing this - I'd like to experiment with FP8 types.

I'm stuck on how to run the example BERT inference with FP8 datatypes -
the instruction given in the readme don't work.

https://github.com/IntelLabs/FP8-Emulation-Toolkit/tree/main/examples/inference/bert

```bash
bash cmd_inference.sh --use_pcl --pcl_bf8 --unpad
```
(note that the script is called `cmd_inference.sh` and  _not_ `cmd_infer.sh` as stated)
(also `download_squad_fine_tuned_model.sh` is not quite right - it's finetuned no hyphen)

The commandline switches `--use_pcl` and `--pcl_bf8` don't exist
(the `--unpad` switch does exist) and I don't find any similar option switches.

The squad baseline inference works for me by running the script with no flags:

```bash
bash cmd_inference.sh
```

How can I run BERT inference with other datatypes?

**Comment by willwray** [comment]
Worked it out straight away this morning.
The script looks for a first argument for the quant_data_type

```
bash cmd_inference.sh e4m3 --unpad
```

It doesn't look like the `--unpad` is passed on to the runner (is it needed or useful?).

**Comment by willwray** [comment]
Now I'm having difficulty doing baseline fp32 or fp16 runs.
Do you have any hints on the most straightforward way to get baseline results?

I've modified the `cmd_inference.py` script to remove the last line `--no_cuda`
in order to run the FP8 emulations on cuda (as I don't have access to recent Xeon)

```
bash cmd_inference.sh fp16
```

fails with

```
Traceback (most recent call last):
  File "FP8-Emulation-Toolkit/examples/inference/bert/run_squad.py", line 1230, in <module>
    main()
  File "FP8-Emulation-Toolkit/examples/inference/bert/run_squad.py", line 1216, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "FP8-Emulation-Toolkit/examples/inference/bert/run_squad.py", line 470, in evaluate
    model, emulator = mpt_emu.quantize_model (model, dtype=args.quant_data_type.lower(), hw_patch='None',
  File "envs/FP_emulation/lib/python3.11/site-packages/mpemu-1.0-py3.11-linux-x86_64.egg/mpemu/mpt_emu.py", line 198, in quantize_model
    raise RuntimeError("mpt_emulator: the requested data type {} is not supported on {}.".format(dtype, device))
RuntimeError: mpt_emulator: the requested data type fp16 is not supported on cuda.
```

then, if I add --fp16 to the `run_squad` args:

```
Traceback (most recent call last):
  File "FP8-Emulation-Toolkit/examples/inference/bert/run_squad.py", line 1230, in <module>
    main()
  File "FP8-Emulation-Toolkit/examples/inference/bert/run_squad.py", line 1143, in main
    raise ImportError(
ImportError: Please install apex from https://www.github.com/nvidia/apex to use fp16 training.
```

then, installing apex is proving hard, and I wasn't planning to do any training at this stage...

**Comment by nkmellem** [comment]
Hi Will, 
Yeah, the readme needs an update, just follow the script cmd_inference.sh. 
You can change the QUANT_TYPE parameter from the script to select the data type. It is set to 'hybrid' at the moment which means E3M4 for weights and E4M3 for activations. You can also use a single data type such as E5M2, E4M3 or INT8 -- all integers sizes are supported. 

Comment out the L468-L473 to disable quantization -- this will give you the baseline. Disabling '--use-cuda' should also work with that change.

**Comment by willwray** [comment]
Thanks, 

Can you share baseline results from a CPU run?

Commenting out those lines from `run_squad.py` gives baseline (with cuda emulation):

```
> bash cmd_inference.sh
...
Results: {'exact': 86.91579943235573, 'f1': 93.1532499015869, 'total': 10570, 'HasAns_exact': 86.91579943235573, 'HasAns_f1': 93.1532499015869, 'HasAns_total': 10570, 'best_exact': 86.91579943235573, 'best_exact_thresh': 0.0, 'best_f1': 93.1532499015869, 'best_f1_thresh': 0.0}
```

compared to these results for e3m4, e4m3, e5m2 and native e3m4-weights,e4m3-activations:

```
> bash cmd_inference.sh  e5m2
...
Results: {'exact': 86.14947965941343, 'f1': 92.56762402756281, 'total': 10570, 'HasAns_exact': 86.14947965941343, 'HasAns_f1': 92.56762402756281, 'HasAns_total': 10570, 'best_exact': 86.14947965941343, 'best_exact_thresh': 0.0, 'best_f1': 92.56762402756281, 'best_f1_thresh': 0.0}

> bash cmd_inference.sh  e4m3
...
Results: {'exact': 86.92526017029329, 'f1': 93.09381141706858, 'total': 10570, 'HasAns_exact': 86.92526017029329, 'HasAns_f1': 93.09381141706858, 'HasAns_total': 10570, 'best_exact': 86.92526017029329, 'best_exact_thresh': 0.0, 'best_f1': 93.09381141706858, 'best_f1_thresh': 0.0}

> bash cmd_inference.sh  e3m4
...
Results: {'exact': 86.77388836329234, 'f1': 93.03849669020896, 'total': 10570, 'HasAns_exact': 86.77388836329234, 'HasAns_f1': 93.03849669020896, 'HasAns_total': 10570, 'best_exact': 86.77388836329234, 'best_exact_thresh': 0.0, 'best_f1': 93.03849669020896, 'best_f1_thresh': 0.0}

> bash cmd_inference.sh hybrid

Results: {'exact': 87.13339640491958, 'f1': 93.22259037975549, 'total': 10570, 'HasAns_exact': 87.13339640491958, 'HasAns_f1': 93.22259037975549, 'HasAns_total': 10570, 'best_exact': 87.13339640491958, 'best_exact_thresh': 0.0, 'best_f1': 93.22259037975549, 'best_f1_thresh': 0.0}
```

The native results beat even the baseline results, which is surprising. Or perhaps there's extra scaling to improve the FP8 results in that case (I've opened up the cited papers to look for clues there).

If you can share baseline results then that'll verify at least that CPU dispatch gives the same results as GPU dispatch.

(I guess that GPU dispatch might not have been tested for the FP16 code path, while
 I guess that the FP8 results were cross-checked to verify the gpu results.)

**Comment by nkmellem** [comment]
CPU baseline : 
 Results: {'exact': 86.91579943235573, 'f1': 93.1532499015869, 'total': 10570, 'HasAns_exact': 86.91579943235573, 'HasAns_f1': 93.1532499015869, 'HasAns_total': 10570, 'best_exact': 86.91579943235573, 'best_exact_thresh': 0.0, 'best_f1': 93.1532499015869, 'best_f1_thresh': 0.0}

I am curious why you are unable to run on a CPU. Can you raise another issue with the error message / stack trace?
